### ISSUE TITLE
可以给个多IP 多入口多出口的配置吗

### ISSUE THREAD

**Issue by woaipo** [Paper-Dragon/muti_xray#6]
多IP 多入口多出口的配置可以给我个吗    我现在出口都是同一个IP 不知道怎么写配置文件。谢谢

**Comment by Paper-Dragon** [comment]
### 您好，这个代码里本身有ip检测机制，使用`ip addr`命令检查你是否有多个公网ip; 同ip多出口机制我这边是没写。。。这个功能在本身程序上略微修改即可实现。
